### ISSUE TITLE
Migrate to Twitch Webhooks API

### ISSUE THREAD

**Issue by micalevisk** [micalevisk/twitchtv-channel-notifier#3]
To replace the current long polling technique 
just subscribe to the topic [stream changed](https://dev.twitch.tv/docs/api/webhooks-reference#topic-stream-changed) and notify when `data.length > 0` (from notify request payload) and the date saved on some sort of storage file is not the same as `data.started_at` (since there is no way to filter only _stream goes online_ event)

This will increase notification reliability, introduces realtime capabilities and decrease the usage of GitHub Actions quota

But GH Actions as storage can no longer be used due to webhook callback constraint ([Vercel Now](https://vercel.com/docs/v2/serverless-functions/introduction), [Netlify](https://www.netlify.com/products/functions), [MongoDB Stitch](https://docs.mongodb.com/stitch/admin/billing/#pricing), [Supabase Function & storage](https://supabase.com/). And keeping state between serveless function invocations will be a problem. To solve this we can use the free tier of [Upstash](https://upstash.com) (Redis-as-a-service), or a Database-as-a-service like: [mLab](https://mlab.com), [FaunaDB cloud](https://fauna.com), [Railway](https://railway.app), [PlanetScale](https://www.planetscale.com), or even the free tier of [Qovery](https://www.qovery.com) to host the entire Nodejs app + using Redis as the main database.

Maybe we can use [External events: `repository_dispatch`](https://help.github.com/en/actions/reference/events-that-trigger-workflows#external-events-repository_dispatch) (via GitHub API) to trigger the workflow run that will use an artifact to keep the state. See [Async workflows with repository dispatch - GitHub Satellite 2020](https://www.youtube.com/watch?v=-xrFNFby7hc)

GH Actions could be used to renew the webhook [subscriptions](https://dev.twitch.tv/docs/api/webhooks-guide#subscriptions) since _"All subscriptions have an expiration time, which cannot exceed 10 days."_

Besides that, we'll can implement a notification for multiple Twitch channels and update the message sent by the bot as well :smiley:

Note that we're looking for a more dependecy-free and slim solution here to reduce the serverless cold start latency -- https://moiva.io to rescue!

---

The happy path workflow will be somewhat like this:
> - **Client**: our temporary HTTP client just send a subscription request (besides the fact that subscriptions should be renew due to its expiration time)
> - **Helix API**: `https://api.twitch.tv/helix` endpoint
> - **Twitch**: the twitch webhook server
> - **Server**: our serverless function that will be used as webhook (`hub.callback` _`X`_ value in **1**, following [this spec](https://dev.twitch.tv/docs/api/webhooks-reference#subscribe-tounsubscribe-from-events))

[![sequence diagram](https://user-images.githubusercontent.com/13461315/95361632-f8f93700-089a-11eb-9719-b7decd273e99.png)][mermaidlink]

---

### TODO to close this issue

- [ ] Choose a serverless host provider for the new serverless/lambda function ~ **must be** free
  + [ ] If the serverless host plataform doesn't comes with some free state management feature, choose one cloud-based _(or use GitHub Actions artifacts)_
- [ ] Implement the code for the serverless function (to handle `GET /` and `POST /` requests from Twitch, and other personal routes for eg: `GET /listen/{channel}` to subscribe using Helix and Webhook APIs). Including the server communication with the storage mechanism
- [ ] Write the GitHub Action that will renew subscriptions ~ using _schedule_ to run every 10 days since some well defined day (the last run)
- [ ] Add a human-friendly diagram to describe _HOW IT WORKS_

---

Example of incoming request from Twitch (step **5**):

```
req url = '/'
req method = 'POST'
req headers = {
  host: 'c56b8fe5.ngrok.io',
  'user-agent': 'Go-http-client/1.1',
  connection: 'close',
  'content-length': '559',
  'content-type': 'application/json; charset=utf-8',
  link: '<https://api.twitch.tv/helix/webhooks/hub>; rel="hub", <https://api.twitch.tv/helix/streams?user_id=433615460>; rel="self"',
  'twitch-notification-id': '88429811-567d-4cfa-85a3-b37b88abe65f',
  'twitch-notification-retry': '0',
  'twitch-notification-timestamp': '2020-05-02T20:03:23Z',
  'x-hub-signature': 'sha256=XYZABC',
  'accept-encoding': 'gzip',
  'x-forwarded-for': '34.218.218.240'
}

{
  data: [
    {
      game_id: '509670',
      id: '1438466417',
      language: 'pt',
      started_at: '2020-05-02T20:00:06Z',
      tag_ids: [Array],
      thumbnail_url: 'https://static-cdn.jtvnw.net/previews-ttv/live_user_codigofalado-{width}x{height}.jpg',
      title: '[BR] Criando um Timer com Vue.js + Novos MEMEs no Canal',
      type: 'live',
      user_id: '433615460',
      user_name: 'CodigoFalado',
      viewer_count: 57
    }
  ]
}
```

[mermaidlink]: https://mermaid-js.github.io/mermaid-live-editor/#/edit/eyJjb2RlIjoic2VxdWVuY2VEaWFncmFtXG4gIGF1dG9udW1iZXJcblxuICByZWN0IHJnYmEoMCwgMjA0LCAyMDQsIC4xKVxuICAgIENsaWVudC0-PitIZWxpeCBBUEk6IFBPU1QgL3dlYmhvb2tzL2h1YlxuICAgIE5vdGUgcmlnaHQgb2YgQ2xpZW50OiBodWIubW9kZT1zdWJzY3JpYmUgICAgICAgICAgICAgICAgICAgIFxuICAgIE5vdGUgcmlnaHQgb2YgQ2xpZW50OiBodWIudG9waWM9aHR0cHM6Ly9hcGkudHdpdGNoLnR2L2hlbGl4L3N0cmVhbXM_dXNlcl9pZD00MzM2MTU0NjBcbiAgICBOb3RlIHJpZ2h0IG9mIENsaWVudDogaHViLmNhbGxiYWNrPSBYXG4gICAgSGVsaXggQVBJLS0-Pi1DbGllbnQ6IFwiXCIgWzIwMl1cbiAgZW5kXG5cbiAgcmVjdCByZ2JhKDAsIDI1NSwgMCwgLjEpXG4gICAgVHdpdGNoLT4-K1NlcnZlcjogR0VUIC8_Y2hhbGxlbmdlPVhZWlxuICAgIE5vdGUgcmlnaHQgb2YgVHdpdGNoOiBzdWJzY3JpcHRpb24gdmVyaWZ5XG4gICAgU2VydmVyLS0-Pi1Ud2l0Y2g6IFwiWFlaXCIgWzJ4eF1cbiAgZW5kXG5cbiAgcmVjdCByZ2JhKDI1NSwgMCwgMjU1LCAuMSlcbiAgICBUd2l0Y2gtPj4rU2VydmVyOiBQT1NUIC9cbiAgICBOb3RlIHJpZ2h0IG9mIFR3aXRjaDogZXZlbnQgbm90aWZ5XG4gICAgU2VydmVyLT4-U2VydmVyOiBjaGVjayBzaWduYXR1cmVcbiAgICBTZXJ2ZXItLT4-LVR3aXRjaDogXCJcIiBbMjAwXVxuICBlbmQiLCJtZXJtYWlkIjp7InRoZW1lIjoiZm9yZXN0IiwidGhlbWVWYXJpYWJsZXMiOnsiYmFja2dyb3VuZCI6IndoaXRlIiwicHJpbWFyeUNvbG9yIjoiI2NkZTQ5OCIsInNlY29uZGFyeUNvbG9yIjoiI2NkZmZiMiIsIm1haW5Ca2ciOiIjY2RlNDk4Iiwic2Vjb25kQmtnIjoiI2NkZmZiMiIsImxpbmVDb2xvciI6IiMwMDAwMDAiLCJib3JkZXIxIjoiIzEzNTQwYyIsImJvcmRlcjIiOiIjNmVhYTQ5IiwiYXJyb3doZWFkQ29sb3IiOiJncmVlbiIsImZvbnRGYW1pbHkiOiJcInRyZWJ1Y2hldCBtc1wiLCB2ZXJkYW5hLCBhcmlhbCIsImZvbnRTaXplIjoiMTZweCIsInRlcnRpYXJ5Q29sb3IiOiJoc2woNzguMTU3ODk0NzM2OCwgNTguNDYxNTM4NDYxNSUsIDg0LjUwOTgwMzkyMTYlKSIsInByaW1hcnlCb3JkZXJDb2xvciI6ImhzbCg3OC4xNTc4OTQ3MzY4LCAxOC40NjE1Mzg0NjE1JSwgNjQuNTA5ODAzOTIxNiUpIiwic2Vjb25kYXJ5Qm9yZGVyQ29sb3IiOiJoc2woOTguOTYxMDM4OTYxLCA2MCUsIDc0LjkwMTk2MDc4NDMlKSIsInRlcnRpYXJ5Qm9yZGVyQ29sb3IiOiJoc2woNzguMTU3ODk0NzM2OCwgMTguNDYxNTM4NDYxNSUsIDc0LjUwOTgwMzkyMTYlKSIsInByaW1hcnlUZXh0Q29sb3IiOiIjMzIxYjY3Iiwic2Vjb25kYXJ5VGV4dENvbG9yIjoiIzMyMDA0ZCIsInRlcnRpYXJ5VGV4dENvbG9yIjoiIzMyMWI2NyIsInRleHRDb2xvciI6IiMwMDAwMDAiLCJub2RlQmtnIjoiI2NkZTQ5OCIsIm5vZGVCb3JkZXIiOiIjMTM1NDBjIiwiY2x1c3RlckJrZyI6IiNjZGZmYjIiLCJjbHVzdGVyQm9yZGVyIjoiIzZlYWE0OSIsImRlZmF1bHRMaW5rQ29sb3IiOiIjMDAwMDAwIiwidGl0bGVDb2xvciI6IiMzMzMiLCJlZGdlTGFiZWxCYWNrZ3JvdW5kIjoiI2U4ZThlOCIsImFjdG9yQm9yZGVyIjoiaHNsKDc4LjE1Nzg5NDczNjgsIDU4LjQ2MTUzODQ2MTUlLCA1NC41MDk4MDM5MjE2JSkiLCJhY3RvckJrZyI6IiNjZGU0OTgiLCJhY3RvclRleHRDb2xvciI6ImJsYWNrIiwiYWN0b3JMaW5lQ29sb3IiOiJncmV5Iiwic2lnbmFsQ29sb3IiOiIjMzMzIiwic2lnbmFsVGV4dENvbG9yIjoiIzMzMyIsImxhYmVsQm94QmtnQ29sb3IiOiIjY2RlNDk4IiwibGFiZWxCb3hCb3JkZXJDb2xvciI6IiMzMjY5MzIiLCJsYWJlbFRleHRDb2xvciI6ImJsYWNrIiwibG9vcFRleHRDb2xvciI6ImJsYWNrIiwibm90ZUJvcmRlckNvbG9yIjoiIzZlYWE0OSIsIm5vdGVCa2dDb2xvciI6IiNmZmY1YWQiLCJub3RlVGV4dENvbG9yIjoiYmxhY2siLCJhY3RpdmF0aW9uQm9yZGVyQ29sb3IiOiIjNjY2IiwiYWN0aXZhdGlvbkJrZ0NvbG9yIjoiI2Y0ZjRmNCIsInNlcXVlbmNlTnVtYmVyQ29sb3IiOiJ3aGl0ZSIsInNlY3Rpb25Ca2dDb2xvciI6IiM2ZWFhNDkiLCJhbHRTZWN0aW9uQmtnQ29sb3IiOiJ3aGl0ZSIsInNlY3Rpb25Ca2dDb2xvcjIiOiIjNmVhYTQ5IiwidGFza0JvcmRlckNvbG9yIjoiIzEzNTQwYyIsInRhc2tCa2dDb2xvciI6IiM0ODdlM2EiLCJ0YXNrVGV4dExpZ2h0Q29sb3IiOiJ3aGl0ZSIsInRhc2tUZXh0Q29sb3IiOiJ3aGl0ZSIsInRhc2tUZXh0RGFya0NvbG9yIjoiYmxhY2siLCJ0YXNrVGV4dE91dHNpZGVDb2xvciI6ImJsYWNrIiwidGFza1RleHRDbGlja2FibGVDb2xvciI6IiMwMDMxNjMiLCJhY3RpdmVUYXNrQm9yZGVyQ29sb3IiOiIjMTM1NDBjIiwiYWN0aXZlVGFza0JrZ0NvbG9yIjoiI2NkZTQ5OCIsImdyaWRDb2xvciI6ImxpZ2h0Z3JleSIsImRvbmVUYXNrQmtnQ29sb3IiOiJsaWdodGdyZXkiLCJkb25lVGFza0JvcmRlckNvbG9yIjoiZ3JleSIsImNyaXRCb3JkZXJDb2xvciI6IiNmZjg4ODgiLCJjcml0QmtnQ29sb3IiOiJyZWQiLCJ0b2RheUxpbmVDb2xvciI6InJlZCIsImxhYmVsQ29sb3IiOiJibGFjayIsImVycm9yQmtnQ29sb3IiOiIjNTUyMjIyIiwiZXJyb3JUZXh0Q29sb3IiOiIjNTUyMjIyIiwiY2xhc3NUZXh0IjoiIzMyMWI2NyIsImZpbGxUeXBlMCI6IiNjZGU0OTgiLCJmaWxsVHlwZTEiOiIjY2RmZmIyIiwiZmlsbFR5cGUyIjoiaHNsKDE0Mi4xNTc4OTQ3MzY4LCA1OC40NjE1Mzg0NjE1JSwgNzQuNTA5ODAzOTIxNiUpIiwiZmlsbFR5cGUzIjoiaHNsKDE2Mi45NjEwMzg5NjEsIDEwMCUsIDg0LjkwMTk2MDc4NDMlKSIsImZpbGxUeXBlNCI6ImhzbCgxNC4xNTc4OTQ3MzY4LCA1OC40NjE1Mzg0NjE1JSwgNzQuNTA5ODAzOTIxNiUpIiwiZmlsbFR5cGU1IjoiaHNsKDM0Ljk2MTAzODk2MSwgMTAwJSwgODQuOTAxOTYwNzg0MyUpIiwiZmlsbFR5cGU2IjoiaHNsKDIwNi4xNTc4OTQ3MzY4LCA1OC40NjE1Mzg0NjE1JSwgNzQuNTA5ODAzOTIxNiUpIiwiZmlsbFR5cGU3IjoiaHNsKDIyNi45NjEwMzg5NjEsIDEwMCUsIDg0LjkwMTk2MDc4NDMlKSJ9fSwidXBkYXRlRWRpdG9yIjpmYWxzZX0

**Comment by micalevisk** [comment]
this will increase realibilty and introduces real-time notifications but github actions cannot be no longer used due to webhook callback. Zeit Now can be use instead.

**Comment by micalevisk** [comment]
For now I'm testing the feasibility of this. Soon I'll be prototyping the new design.
